theme: jekyll-theme-slate
title: Formation
description: Une sélection de présentations et de documents de formation
show_downloads: false
google_analytics: [Your Google Analytics tracking ID]
lang: fr-FR
